### ISSUE TITLE
How to perform non-GET request to related resource

### ISSUE THREAD

**Issue by quimrstorres** [pezra/hal-client#41]
Is there a way to perform a non-GET request to a related resource (with an interface similar to `#related`)? I realize I can call `#related` and then call `#post` in the `RepresentationSet`, but I wanted to avoid the first GET request altogether.

Maybe I am missing something in the documentation but I've been struggling a bit with this.

**Comment by pezra** [comment]
There is not an easy way to do exactly what you are asking. Generally it is
not required because `#related` does not make a request until the client
accesses the properties or links. That is, `HalClient::Representation` is
lazy and delays request until it is absolutely required. This means that
`my_rep.related("history").post(new_history_entry_hal)` only makes one http
request which is the POST request.

If you really need this you could do something like
`my_rep.hal_client.post(my_rep.related_hrefs("history").first, body)`.

Is there a way to perform a non-GET request to a related resource (with an
interface similar to #related)? I realize I can call #related and then call
#post in the RepresentationSet, but I wanted to avoid the first GET request
altogether.

Maybe I am missing something in the documentation but I've been struggling
a bit with this.

—
Reply to this email directly or view it on GitHub
<https://github.com/pezra/hal-client/issues/41>.

**Comment by quimrstorres** [comment]
Yeah, what you mentioned is what I needed. I was being silly, sorry.

I have only another question, if you don't mind. Is there any particular reason why `#post` (and similar methods) receive a JSON string or something that responds to `#to_hal`? Would it make sense to receive a `Hash` and internally create the JSON string?

**Comment by quimrstorres** [comment]
Oh, and thanks for your explanation.

**Comment by pezra** [comment]
I think it would be reasonable for post and put to fall back on `#to_json`
if `#to_hal`is not defined. In my usage I tend not to use hashes much but I
don't see issue with the approach. I'd definitely merge a PR to that effect.

**Comment by quimrstorres** [comment]
Awesome! Will also close this one and come back to you as soon as possible. :+1:
