### ISSUE TITLE
CURIES are misunderstood?

### ISSUE THREAD

**Issue by bubenkoff** [pezra/hal-client#45]
According to the HAL specification, CURIES are for the documentation
http://stateless.co/hal_specification.html
while hal-client uses them as link identifiers
Isn't there a misconcept implemented in hal-client?
My hal api exposes links with curies like:

```javascript
"_links": {
  "curies": [
    {
      "name": "doc",
      "href": "http://haltalk.herokuapp.com/docs/{rel}",
      "templated": true
    }
  ],

  "doc:latest-posts": {
    "href": "/posts/latest"
  }
}
```
so i want to be able to access the `latest-posts` links via `doc:latest-posts` and not via the full documentation URI, which makes the client code really strange

**Comment by pezra** [comment]
You should be able to use `doc:latest-posts` to access the link in the example. If that doesn't work it is a bug.

The other, more complicated, lookup patterns allow the use of those rels as proper [CURIE](http://www.w3.org/TR/curie/)s. Based on the name and a certain vagueness in the spec i believed that this was the intent. The spec's author has since stated that he did not intend for CURIEd rels to be treated as CURIEs. This makes me sad, because it is a poorer choice for interoperability and evolvability, so i have not taken the time to remove it from hal-client.

PS: If you are going to do this i'd suggest replacing "doc" with a more application specific prefix.

**Comment by bubenkoff** [comment]
Yes, im not able to access the link by it's key name, that's why i created this issue
It fails with key error

**Comment by bubenkoff** [comment]
thanks!
can you please make a new release?

**Comment by pezra** [comment]
Already done. :) Version 3.12.0 includes this fix. Thanks for the report.
